app:
  datasource:
    jdbcUrl:  jdbc:mysql://localhost/app
    username: root
    password: root

auth:
  datasource:
    jdbcUrl:  jdbc:mysql://localhost/auth
    username: root
    password: root
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url:
#    username:
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
