app:
  datasource:
    jdbcUrl:  jdbc:mysql://localhost:3306/app
    username: root
    password: root

auth:
  datasource:
    jdbcUrl:  jdbc:mysql://localhost:3306/auth
    username: root
    password: root

jpa:
  hibernate:
    ddl-auto: update
