CREATE SEQUENCE SEQ_AUTORES START WITH 1 INCREMENT BY 1;
CREATE TABLE AUTORES
    (
        ID INTEGER NOT NULL,
        NOME VARCHAR(255) NOT NULL,
        SEXO VARCHAR(20),
        EMAIL VARCHAR(355) NOT NULL,
        DATA_NASCIMENTO TIMESTAMP NOT NULL,
        PAIS_ORIGEM VARCHAR(255) NOT NULL,
        CPF VARCHAR(20),
        PRIMARY KEY (ID)
    );

CREATE SEQUENCE SEQ_OBRAS START WITH 1 INCREMENT BY 1;
CREATE TABLE OBRAS
    (
        ID INTEGER NOT NULL,
        FK_AUTOR NUMBER(10,0),
        NOME VARCHAR(255) NOT NULL,
        DESCRICAO VARCHAR(1000) NOT NULL,
        IMAGEM VARCHAR(1000) NOT NULL,
        DATA_PUBLICACAO TIMESTAMP NOT NULL,
        DATA_EXPOSICAO TIMESTAMP NOT NULL,
        PRIMARY KEY (ID)
    );

ALTER TABLE OBRAS ADD CONSTRAINT FK_AUTOR_OBRA FOREIGN KEY (FK_AUTOR) REFERENCES AUTORES(ID);